dataset:
  filename: "glue"
  subset: "cola"
  filepath:
  label_map: [0, 1, 2, 3]
  batch_size: 10
  num_workers: 1
  train: "train"
  validation: "validation"
  test: "validation"
  feature1: "sentence"
  feature2:
  label: "label"
  max_length: 128

model:
  vocab_size: 30522
  index: 7
  hidden_dim: 64
  kernel_size: [ 5, 3, 3, 3, 3, 3, 3, 7 ]
  dilation: [ 1, 1, 1, 1, 1, 1, 1, 1 ]
  padding: [ 2, 1, 1, 1, 1, 1, 1, 3 ]
  n_heads: 2
  num_mixers: 2
  max_seq_len: ${dataset.max_length}
  num_classes: 2
  num_models: [1, 1, 1]
  model_flag: [0, 1, 2]
  num_layers: [40, 42, 42]